### ISSUE TITLE
Собрать презентацию в проекте и в powerpoint

### ISSUE THREAD

**Issue by m3tro1d** [m3tro1d/entrepresenteur#71]
Нужно собрать одинаковые презентации в нашем проекте и в powerpoint, чтобы лучше оценить, чего нам не хватает. Отписать в задачу обратную связь:
1. Что работает хорошо и проблем не возникает;
2. Что работает не очень и мешает созданию презентации;
3. Чего, возможно, не хватает для более удобной работы в приложении.

**Comment by NoSiReapo** [comment]
https://docs.google.com/document/d/1y3TLiysU6qPzrImchbFGKyWYVO9we0wvZ8I_f_KWuGA/edit?usp=sharing
